apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: radius
    name: radius
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: radius:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ubuntu:16.04
      type: Docker
    triggers:
    - github:
        secret: SaBPXb6tW4J5eZAtdCX1
      type: GitHub
    - generic:
        secret: hSMJ3LIulh3Syz0O6-5O
      type: Generic
  status:
    lastVersion: 0
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
