apiVersion: v1
kind: Service
metadata:
  labels:
    app: radius
  name: radius
spec:
  ports:
  - name: 1812-udp
    port: 1812
    protocol: UDP
    targetPort: 1812
  - name: 1813-udp
    port: 1813
    protocol: UDP
    targetPort: 1813
  selector:
    app: radius
    deploymentconfig: radius
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
